### ISSUE TITLE
Email String Is Empty

### ISSUE THREAD

**Issue by Luidog** [geistinteractive/edd-sl-caching-proxy-js#4]
I found that it is possible for a user's email to be an empty but defined string. This would cause the checkLicenses function to return a 401 (rightfully).  

Since the main responsibility of this library is authentication  and retrieval of a user's licenses  think email should be required to either contain a value or not exist as a key the login method's returned object.

**Comment by toddgeist** [comment]
That shouldn't be possible. Can you explain exactly when the email is empty?

Todd

**Comment by Luidog** [comment]
Using the test account after logging in the response back contains a null email address. The response seems to be firebase account.

**Comment by toddgeist** [comment]
That is not a firebase account

**Comment by toddgeist** [comment]
do you mean when you call EDD.login(userName, Password), there is no email in the response?

**Comment by Luidog** [comment]
I mean the `loginForFirebase` function. It is currently returning a null email address on the test account.

**Comment by toddgeist** [comment]
That shouldn't be possible and is not what I see here.  I'll have to look

**Comment by toddgeist** [comment]
Works for me.  Perfectly

```
eddsl
  .loginForFirebase("toddgeist@gmail.com", "id7Dh0VppRBi8%QaUf@3oUeU")
  .then(result => {
    console.log(result);
  })
  .catch(e => {
    console.log(e);
  });
```
this is what I get.  Which as you can see includes the email.
```
{ token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1MDEiLCJpYXQiOjE1MTgzMDg3NzMsImV4cCI6MTUxODMxMjM3MywiYXVkIjoiaHR0cHM6Ly9pZGVudGl0eXRvb2xraXQuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmlkZW50aXR5LmlkZW50aXR5dG9vbGtpdC52MS5JZGVudGl0eVRvb2xraXQiLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay01amxqYkBmbXFibzMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJmaXJlYmFzZS1hZG1pbnNkay01amxqYkBmbXFibzMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20ifQ.WjOTclpsX5hNPmk2Df38bKIKqNJdd6D-Oja_2kz-QsMYrABJpVIzlSVRL6s64S6wJh7U0ZpYELr6m-B45TCxh02D-AEVg9803MPo4ID4KOFfrBtMGLHrvueo2piEq1lNEXWYLG8En-G_ZGFx9Pcm-HmIPB6DOUzmyfcwhbh3iPqpEqsxejYB6HSM-w3x1iwP9QD0tImt5c7fErJfYsm18W49ivb0-So9MHtbFQjVtlK6O9i1AqE2tSHZO9h_EpOHf8p4zGQo4tNT29YyscCJNLyXBNMkGBQsbySYUlalpTbtYe_LOvEFEq8UdRSJbRN0dT_NfolyYnPiOLssSiEdOw',
  userID: '501',
  email: 'toddgeist@gmail.com',
  login: 'toddtest',
  displayName: 'test test' }
```

Is this not what you get?

**Comment by Luidog** [comment]
Todd,

I was looking at the wrong response. On the FM-QBO admin site once a user logs in I redirect to the account page. This redirect was happening directly after login, so it look like  the `.loginForFirebase`  response was missing the email address. 

It is actually `fire.auth().onAuthStateChanged()` is return the empty email.

It looks like the problem is that in Firebase the email is not being saved. I took a look at the admin console and found that the email account is indeed blank there. 

Here is a screenshot:

![screen shot 2018-02-10 at 8 11 23 pm](https://user-images.githubusercontent.com/6627284/36069437-9964e076-0e9e-11e8-8ed4-ffd1522c860e.png)

Would it be possible to set the firebase user email address when you sign a custom token for the user? Getting the firebase user  email address alongside the firebase auth information reduces the code complexity significantly.

It looks like a call to `admin.auth().updateUser(uid, {})` after the user account is created would allow the email to be added.

**Comment by toddgeist** [comment]
I added the email address to the "claims" key in the token, but I don't think this will help. claims are used for security rules, not for filling out the profile.  You are still going to have to fill out the profile, I think.

**Comment by Luidog** [comment]
I added two methods to fm-qbo admin to support updating the firebase user profile. This is currently in place at this branch: https://github.com/geistinteractive/fmqbo-3-admin-site/commit/9e494c3499f0f6e1150d2323e8327c13113cb4db
