### ISSUE TITLE
EDD-SL License Activation Failing

### ISSUE THREAD

**Issue by Luidog** [geistinteractive/edd-sl-caching-proxy-js#6]
I am having trouble activating a license using the following method:

https://geistinteractive.github.io/edd-sl-caching-proxy-js/classes/eddsl.html#licenseactivate

I am receiving the following response from the library:

```
activations_left: 3,
checksum: "5207e9080ad191575ea05bc9ef6c203d",
customer_email: "toddgeist@gmail.com",
customer_name: "test test",
error: "invalid_item_id",
expires: "2018-02-28 23:59:59",
item_name: "test-monthly &#8211; toddgeist@gmail.com",
license: "invalid",
license_limit: 3,
payment_id: "326023",
price_id: false,
site_count: 0,
success: false
```

I believe this is because I am using the wrong activationId. I have tried using a uuid string and the product name as activation ids.

What should FM-QBO3-Admin use for an activation id? 

Also the `edd.licenseActivate` method takes a license property which is a string.

 Is this the `response.license.key` value from the `edd.userLicenses` method the right value to use?

**Comment by toddgeist** [comment]
the activationID is the QBO company ID

Each activation is good for a single QBO Company ID

**Comment by toddgeist** [comment]
the itemID is 326025

**Comment by Luidog** [comment]
@toddgeist  I just tried to use the QBO companyId and still received a falling response. To clarify I attempted to use the following parameters activate a license and still received an invalid id error response.

![screen shot 2018-02-25 at 8 25 38 pm](https://user-images.githubusercontent.com/6627284/36653453-1195e64a-1a6a-11e8-897e-0b62e2cbb7ee.png)

**Comment by toddgeist** [comment]
I found it.  Somehow that ItemId in the "Test Accounts" doc was wrong. I must have copied it wrong.
it should have been `326015` not `326025`.

Sorry about that

Here is an example that works
https://gist.github.com/toddgeist/269596664461e8ddda3f22e030c73c2d

**Comment by toddgeist** [comment]
Let's try to make use of gists or explicit code examples when we communicate.  That might help clear up the issues faster.

**Comment by Luidog** [comment]
Thanks @toddgeist using the correct id worked. Also, I agree, lets use gists from here on out
